locale: "en-US"
title: Zhou Zhou's Blog # Title of your site
url: "https://zhou6140919.github.io/" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
google_analytics_key: ""

# Default description in social shares for the jekyll-seo-tag gem
description: > # this means to ignore newlines until "baseurl:"
  I am a Human.
  My name is Zhou Tong.
  You can call me Zhou Zhou as the same pronunciation from the マンガ JoJo's Bizarre Adventure.

# Author details for the jekyll-seo-tag gem
author:
  name: Zhou Tong
  email: zhoutong614@emails.bjut.edu.cn
  twitter: # twitter username without the @ symbol

# Social details for the jekyll-seo-tag gem
social:
  name: Zhou Tong
  links:
    - https://github.com/zhou6140919

permalink: pretty

gems:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-sitemap"

# Jekyll SEO Tag
webmaster_verifications:
  google: # 1234
  bing: # 1234
  alexa: # 1234
  yandex: # 1234

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
